-- MySQL Script generated by MySQL Workbench
-- Thu May 19 19:17:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Revenda_Carr0
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Revenda_Carr0` ;

-- -----------------------------------------------------
-- Schema Revenda_Carr0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Revenda_Carr0` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Revenda_Carr0` ;

-- -----------------------------------------------------
-- Table `Carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Carro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Ano` INT(10) NOT NULL,
  `KM` VARCHAR(50) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCarro`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome_Cliente` VARCHAR(45) NOT NULL,
  `Telefone` INT(12) NOT NULL,
  `CPF` INT(15) NOT NULL,
  `RG` INT(15) NOT NULL,
  `Endereco` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Revenda_Filial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Revenda_Filial` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Revenda_Filial` (
  `idRevenda` INT NOT NULL AUTO_INCREMENT,
  `Cidade` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Qtd_Carros` VARCHAR(45) NOT NULL,
  `Qtd_Vendedores` VARCHAR(45) NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idRevenda`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Revenda_Principal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Revenda_Principal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Revenda_Principal` (
  `idRevenda_Principal` INT NOT NULL AUTO_INCREMENT,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  `Qtd_Carros` INT(45) NOT NULL,
  `Qtd_Vendedores` INT(45) NOT NULL,
  `Revenda_Filial_idRevenda` INT NOT NULL,
  `Vendedor_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idRevenda_Principal`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Venda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `Valor` INT(80) NOT NULL,
  `Forma_Pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVenda`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Venda_has_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Venda_has_Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Venda_has_Cliente` (
  `Venda_idVenda` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Venda_idVenda`, `Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `Nome_Vendedor` VARCHAR(45) NOT NULL,
  `CPF` INT(15) NOT NULL,
  `RG` INT(20) NOT NULL,
  `Endereco` VARCHAR(80) NOT NULL,
  `Telefone` INT(12) NOT NULL,
  `CEP` INT(15) NOT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vendedor_has_Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendedor_has_Venda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vendedor_has_Venda` (
  `Vendedor_idVendedor` INT NOT NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`Vendedor_idVendedor`, `Venda_idVenda`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
